name             'rails-vagrant-vm'
maintainer       'mtsmfm'
maintainer_email 'mtsmfm@gmail.com'
license          'All rights reserved'
description      'Installs/Configures rails-vagrant-vm'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends          'git'
depends          'heroku'
depends          'postgresql'
depends          'rbenv'
depends          'tmux'
depends          'vim'
depends          'zsh'
